# render.yaml
databases:
  - name: ss-scraper-db
    databaseName: ss_scraper_db
    plan: free

services:
  - type: web
    name: ss-scraper
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ss-scraper-db
          property: connectionString

cronJobs:
  - name: scrape-all
    schedule: "0 */2 * * *"  # every 2 hours
    env: node
    buildCommand: npm run build
    startCommand: npm run scrape-all
